In [1]:
import numpy as np

In [2]:
# 一维数组：[1, 3, 5, 7, 9, 11, 13, 15]
arr1 = np.array([1, 3, 5, 7, 9, 11, 13, 15])
print(arr1)

[ 1  3  5  7  9 11 13 15]


In [3]:
# 二维数组：3 行 4 列 全1 数组
arr2 = np.ones((3, 4))
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# 三维数组：2×3×4随机整数数组（0–10）
arr3 = np.random.randint(0, 11, size=(2, 3, 4))
print(arr3)

[[[ 9  3  2  1]
  [ 4 10 10  9]
  [ 5  8  2  1]]

 [[ 3 10  6  0]
  [ 9 10  4  2]
  [ 6  1  1  4]]]


In [5]:
# 分别输出每个数组的形状、数据类型、元素总数     （切记拼接的时候不要用 + ，只有两边都是字符串才可以用，不然就报错 或者用str()转换一下 ）
# print("arr1 数组的形状:" + arr1.shape + "arr1 数组的数据类型:"+ arr1.dtype + "arr1 数组的元素总数:" + arr1.size)
print(f"arr1 数组的形状:{arr1.shape} \t\t\t 数据类型: {arr1.dtype} \t\t 元素总数:{arr1.size}")
print(f"arr2 数组的形状:{arr2.shape} \t\t 数据类型: {arr2.dtype} \t 元素总数:{arr2.size}")
print(f"arr3 数组的形状:{arr3.shape} \t 数据类型: {arr3.dtype} \t\t 元素总数:{arr3.size}")

arr1 数组的形状:(8,) 			 数据类型: int64 		 元素总数:8
arr2 数组的形状:(3, 4) 		 数据类型: float64 	 元素总数:12
arr3 数组的形状:(2, 3, 4) 	 数据类型: int32 		 元素总数:24


第二题

In [6]:
arr = np.arange(24).reshape(4, 6)
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [7]:
# 获取第2行所有元素
l2 = arr[1, :]
print(l2)

[ 6  7  8  9 10 11]


In [8]:
# 获取第3列所有元素
c3 = arr[:, 2]
print(c3)

[ 2  8 14 20]


In [9]:
# 获取第1–3行、第2–5列的子数组
cl = arr[:3, 1:5]
print(cl)

[[ 1  2  3  4]
 [ 7  8  9 10]
 [13 14 15 16]]


In [10]:
# 用布尔索引筛选所有大于15的元素
a = arr[arr > 15]
print(a)

[16 17 18 19 20 21 22 23]


第三题

In [11]:
#  将 `a = np.array([1,2,3,4,5])` 转为5×1二维数组
a = np.array([1,2,3,4,5])
a1 = a.reshape(5, 1)
print(a1)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [12]:
# 计算 `b = [[1,2,3],[4,5,6],[7,8,9]]` 与 `c = [10,20,30]` 的广播加法
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.array([10,20,30])
res = b + c     #   c = np.array([10,20,30],[10,20,30],[10,20,30])  直接对应位置的数相加
print(res)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [13]:
# 将 `d = np.random.randint(0,100,20)` 转为4×5并转置
d = np.random.randint(0,100,20)
d1 = d.reshape(4, 5)
print(d1,end="\n\n")
d2 = d1.T
print(d2)

[[58 22 95 42 92]
 [40 43 34 14 13]
 [56 76  7 18 87]
 [34 84 58 59 45]]

[[58 40 56 34]
 [22 43 76 84]
 [95 34  7 58]
 [42 14 18 59]
 [92 13 87 45]]


第四题

In [14]:
# 成绩数组 `scores = np.array([[85,92,78,90],[76,88,95,82],[93,80,87,91]])`
scores = np.array([[85,92,78,90],
                   [76,88,95,82],
                   [93,80,87,91]])

In [15]:
# 计算每门课平均分、最高分、最低分
smean = scores.mean(axis=1)
smax = scores.max(axis=1)       # axis=0 是竖着算

smin = scores.min(axis=1)
print(f"每门课平均分：{smean}  最高分：{smax}  最低分：{smin}")

每门课平均分：[86.25 85.25 87.75]  最高分：[92 95 93]  最低分：[78 76 80]


In [16]:
# 计算每个学生总分与平均分
ssum = scores.sum(axis=1)
print(f"每个学生总分：{ssum}  平均分：{smean}")

每个学生总分：[345 341 351]  平均分：[86.25 85.25 87.75]


In [17]:
# 找出所有>90分的位置
print(np.where(scores > 90))    # 可以类比坐标 （1，2），（2，2），（0，1），（3，0）

(array([0, 1, 2, 2]), array([1, 2, 0, 3]))


In [18]:
# 计算所有成绩的标准差与方差
STD = np.std(scores)
VAR = np.var(scores)
print(f"所有成绩标准差：{STD}  方差：{VAR}")

所有成绩标准差：5.964594612284131  方差：35.576388888888886


第五题

In [19]:
np.random.seed(2026)
height = np.random.normal(165,8,50).round(1)
weight = np.random.normal(55,10,50).round(1)

In [20]:
BMI = weight / (height/100) ** 2
BMI = np.round(BMI, 2)
print(BMI)

[19.25 19.   11.73 22.32  7.15 21.45 25.55 19.3  20.99 23.56 23.01 19.74
 26.35 19.2  16.44 17.86 21.21 20.65 18.2  21.17 18.69 19.19 28.48 17.5
 20.76 27.   20.32 16.39 19.96 25.09 20.11 22.01 25.86 16.01 22.72 22.69
 17.37 29.23 20.78 23.12 26.52 17.69 14.08 21.37 19.09 18.54 24.84 25.97
 16.96 16.01]


In [21]:
# 按标准分类：偏瘦/正常/超重/肥胖
a = BMI < 18               # 偏瘦
b = (BMI>=18) & (BMI<24) # 正常
c = (BMI>=24) & (BMI<28)   # 超重
d = BMI >=28                # 肥胖

In [22]:
# 统计各类别人数与占比
total = 50
c1 = np.sum(a)
c2 = np.sum(b)
c3 = np.sum(c)
c4 = np.sum(d)

# 统计占比
r1 = np.round(c1 / total * 100, 2)
r2 = np.round(c2 / total *100, 2)
r3 = np.round(c3 / total *100, 2)
r4 = np.round(c4 / total *100, 2)

In [23]:
print("偏瘦", c1, f"{r1}%")
print("正常", c2, f"{r2}%")
print("超重", c3, f"{r3}%")
print("肥胖", c4, f"{r4}%")

偏瘦 12 24.0%
正常 28 56.0%
超重 8 16.0%
肥胖 2 4.0%


In [24]:
# 输出身高前5名的BMI数据
top_index = np.argsort(height)[::-1][:5]
print(f"身高前5位的位置：{top_index}")
top_BMI = BMI[top_index]
print(f"身高前5名的BMI数据：{top_index}")

身高前5位的位置：[27 18 45 23 42]
身高前5名的BMI数据：[27 18 45 23 42]


拓展

In [25]:
# 实现二维数组按行/按列分别求和、求均值
arr = np.random.randint(60, 101, size=(2, 2))
print(arr)

csum = arr.sum(axis=0)
cmean = arr.mean(axis=0)

rsum = arr.sum(axis=1)
rmean = arr.mean(axis=1)

print("按列求和：", csum)
print("按列均值：", cmean)
print("按行求和：", rsum)
print("按行均值：", rmean)

[[91 62]
 [80 85]]
按列求和： [171 147]
按列均值： [85.5 73.5]
按行求和： [153 165]
按行均值： [76.5 82.5]


In [26]:
#用NumPy实现简单线性回归预测
